#Shangyu Chen
#specify role for nectar
---
#- hosts: remote
- hosts: localhost

#- hosts: remote
#  connection: local
#  become: yes
#  become_user: root
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    #- role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    #- role: create-inventory
#    - role: openstack-security-group
    