#Shangyu Chen
#varibles for nectar
# Common vars
availablility_zone: melbourne-qh2-uom

#Volume
volumes:
  - vol_name: vol-1
    vol_size: 10
  - vol_name: vol-2
    vol_size: 10

#Security group
security_groups:
  - name: ssh_ass2
    description: "for ssh access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_ass2
    description: "for HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

#Instance
instance_name: DataHarvest
instance_image: 0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5
instance_key_name: wifitrack
instance_flavor: uom.general.2c8g

